//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.example.crackhash.schemes;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.crackhash.schemes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.crackhash.schemes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CrackHashWorkerResponse }
     * 
     * @return
     *     the new instance of {@link CrackHashWorkerResponse }
     */
    public CrackHashWorkerResponse createCrackHashWorkerResponse() {
        return new CrackHashWorkerResponse();
    }

    /**
     * Create an instance of {@link CrackHashWorkerResponse.Answers }
     * 
     * @return
     *     the new instance of {@link CrackHashWorkerResponse.Answers }
     */
    public CrackHashWorkerResponse.Answers createCrackHashWorkerResponseAnswers() {
        return new CrackHashWorkerResponse.Answers();
    }

}
